// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using THONK.Database;

namespace THONK.Migrations
{
    [DbContext(typeof(SQLiteDBContextStore))]
    partial class SQLiteDBContextStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("THONK.Database.GuildUsers", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("UsersId");

                    b.HasKey("GuildId");

                    b.HasIndex("UsersId");

                    b.ToTable("GuildUsers");
                });

            modelBuilder.Entity("THONK.Database.GuildsConfig", b =>
                {
                    b.Property<ulong>("GuildID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("ChannelAnnouncements");

                    b.Property<ulong>("ChannelBotLog");

                    b.Property<ulong>("ChannelGeneral");

                    b.Property<ulong>("ChannelLog");

                    b.Property<string>("Prefix");

                    b.HasKey("GuildID");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("THONK.Database.UserRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Warnings");

                    b.HasKey("Id");

                    b.ToTable("UserRecord");
                });

            modelBuilder.Entity("THONK.Database.GuildUsers", b =>
                {
                    b.HasOne("THONK.Database.UserRecord", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId");
                });
#pragma warning restore 612, 618
        }
    }
}
